[package]
name = "dns"
version = "0.3.0"
authors = ["andrei-marinica <andrei.marinica@elrond.com>"]
edition = "2018"

[dependencies]
elrond-wasm = "0.6.0"
elrond-wasm-node = "0.6.0"
elrond-wasm-derive = "0.6.0"

elrond-wasm-module-features = "0.6.0"

# elrond-wasm = { path = "../../elrond-wasm-rs/elrond-wasm" }
# elrond-wasm-node = { path = "../../elrond-wasm-rs/elrond-wasm-node" }
# elrond-wasm-derive = { path = "../../elrond-wasm-rs/elrond-wasm-derive" }
