[package]
name = "dns"
version = "0.3.0"
authors = ["andrei-marinica <andrei.marinica@elrond.com>"]
edition = "2018"

[features]
wasm-output-mode = [
    "elrond-wasm-node",
    "elrond-wasm-module-features-wasm",
]

default = [
    "elrond-wasm-module-features-default",
]

[dependencies]
elrond-wasm-module-features-wasm = { package = "elrond-wasm-module-features", version = "0.9.6", features = ["wasm-output-mode"], default-features = false, optional = true }
elrond-wasm-module-features-default = { package = "elrond-wasm-module-features", version = "0.9.6", optional = true }

elrond-wasm = "0.9.6"
elrond-wasm-derive = "0.9.6"
elrond-wasm-node = { version = "0.9.6", optional = true }

[dev-dependencies]
elrond-wasm-debug = "0.9.6"
