[package]
name = "dns-abi"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@elrond.com>"]
edition = "2018"
publish = false

[dependencies.dns]
path = ".."

[dependencies.elrond-wasm]
version = "0.14.2"

[dependencies.elrond-wasm-debug]
version = "0.14.2"
